// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AgeClassificationIcon: typeof import('./src/components/anime/AgeClassificationIcon.vue')['default']
    AnimeCarousel: typeof import('./src/components/anime/carousel/AnimeCarousel.vue')['default']
    AnimeCarouselTabless: typeof import('./src/components/anime/carousel/AnimeCarouselTabless.vue')['default']
    AnimeDetails: typeof import('./src/components/recommendation/AnimeDetails.vue')['default']
    AnimeDetailsHeader: typeof import('./src/components/recommendation/AnimeDetailsHeader.vue')['default']
    AnimeGridGeneral: typeof import('./src/components/search/AnimeGridGeneral.vue')['default']
    AnimeGridUser: typeof import('./src/components/search/AnimeGridUser.vue')['default']
    AnimeGroupDetails: typeof import('./src/components/recommendation/AnimeGroupDetails.vue')['default']
    AnimeGroupModal: typeof import('./src/components/modal/AnimeGroupModal.vue')['default']
    AnimeItem: typeof import('./src/components/anime/AnimeItem.vue')['default']
    AnimeItemMobile: typeof import('./src/components/anime/AnimeItemMobile.vue')['default']
    copy: typeof import('./src/components/anime/AnimeItem copy.vue')['default']
    Header: typeof import('./src/components/home/Header.vue')['default']
    HomeNavBar: typeof import('./src/components/home/nav/HomeNavBar.vue')['default']
    HomeNavItem: typeof import('./src/components/home/nav/HomeNavItem.vue')['default']
    HomeTabs: typeof import('./src/components/home/HomeTabs.vue')['default']
    IconTablerArrowLeft: typeof import('~icons/tabler/arrow-left')['default']
    IconTablerArrowNarrowRight: typeof import('~icons/tabler/arrow-narrow-right')['default']
    IconTablerCameraOff: typeof import('~icons/tabler/camera-off')['default']
    IconTablerChevronDown: typeof import('~icons/tabler/chevron-down')['default']
    IconTablerChevronLeft: typeof import('~icons/tabler/chevron-left')['default']
    IconTablerChevronRight: typeof import('~icons/tabler/chevron-right')['default']
    IconTablerChevronUp: typeof import('~icons/tabler/chevron-up')['default']
    IconTablerForbid: typeof import('~icons/tabler/forbid')['default']
    IconTablerLogin: typeof import('~icons/tabler/login')['default']
    IconTablerLogout: typeof import('~icons/tabler/logout')['default']
    IconTablerMenu2: typeof import('~icons/tabler/menu2')['default']
    IconTablerMinus: typeof import('~icons/tabler/minus')['default']
    IconTablerPlus: typeof import('~icons/tabler/plus')['default']
    IconTablerSearch: typeof import('~icons/tabler/search')['default']
    IconTablerUser: typeof import('~icons/tabler/user')['default']
    IconTablerX: typeof import('~icons/tabler/x')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LoadingModal: typeof import('./src/components/modal/LoadingModal.vue')['default']
    NotFound: typeof import('./src/components/error/NotFound.vue')['default']
    RecommendationList: typeof import('./src/components/recommendation/RecommendationList.vue')['default']
    RecommendedItem: typeof import('./src/components/recommendation/RecommendedItem.vue')['default']
    RelatedList: typeof import('./src/components/recommendation/RelatedList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastModal: typeof import('./src/components/modal/ToastModal.vue')['default']
    UserIcon: typeof import('./src/components/home/UserIcon.vue')['default']
  }
}
