// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AgeClassificationIcon: typeof import('./src/components/anime/AgeClassificationIcon.vue')['default']
    AnimeCarousel: typeof import('./src/components/anime/carousel/AnimeCarousel.vue')['default']
    AnimeCarouselTabless: typeof import('./src/components/anime/carousel/AnimeCarouselTabless.vue')['default']
    AnimeHoverModal: typeof import('./src/components/anime/carousel/AnimeHoverModal.vue')['default']
    AnimeItem: typeof import('./src/components/anime/AnimeItem.vue')['default']
    BaseModal: typeof import('./src/components/modal/BaseModal.vue')['default']
    copy: typeof import('./src/components/anime/carousel/AnimeCarousel copy.vue')['default']
    Header: typeof import('./src/components/home/Header.vue')['default']
    HeaderCarousel: typeof import('./src/components/anime/carousel/HeaderCarousel.vue')['default']
    HeaderFilter: typeof import('./src/components/anime/HeaderFilter.vue')['default']
    HomeNavBar: typeof import('./src/components/home/nav/HomeNavBar.vue')['default']
    HomeNavItem: typeof import('./src/components/home/nav/HomeNavItem.vue')['default']
    HomeTabs: typeof import('./src/components/home/HomeTabs.vue')['default']
    IconTablerArrowLeft: typeof import('~icons/tabler/arrow-left')['default']
    IconTablerArrowNarrowRight: typeof import('~icons/tabler/arrow-narrow-right')['default']
    IconTablerChevronDown: typeof import('~icons/tabler/chevron-down')['default']
    IconTablerChevronLeft: typeof import('~icons/tabler/chevron-left')['default']
    IconTablerChevronRight: typeof import('~icons/tabler/chevron-right')['default']
    IconTablerLogin: typeof import('~icons/tabler/login')['default']
    IconTablerLogout: typeof import('~icons/tabler/logout')['default']
    IconTablerPlus: typeof import('~icons/tabler/plus')['default']
    IconTablerSearch: typeof import('~icons/tabler/search')['default']
    IconTablerUser: typeof import('~icons/tabler/user')['default']
    IconTablerX: typeof import('~icons/tabler/x')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LoadingModal: typeof import('./src/components/modal/LoadingModal.vue')['default']
    NavBar: typeof import('./src/components/home/nav/NavBar.vue')['default']
    NavItem: typeof import('./src/components/home/nav/NavItem.vue')['default']
    RecommendationCarousel: typeof import('./src/components/RecommendationCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabNavigation: typeof import('./src/components/TabNavigation.vue')['default']
    ToastModal: typeof import('./src/components/modal/ToastModal.vue')['default']
    UserIcon: typeof import('./src/components/home/UserIcon.vue')['default']
  }
}
