version: '3.9'

services:
    frontend:
        container_name: animmendation_frontend
        build:
            context: ..
            dockerfile: .docker/Dockerfile
        volumes:
            - ..:/home/node/app
        ports:
            - 3000:3000
        entrypoint: /entrypoint.sh
        command: tail -f /dev/null
        extra_hosts:
            - host.docker.internal:host-gateway
        tty: true
