name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_VITE_MAL_CLIENT_ID: ${{ secrets.VITE_MAL_CLIENT_ID }}
        envkey_VITE_API_URL: ${{ secrets.VITE_API_URL }}
        env_key_VITE_TRANSLATOR_URL: ${{ secrets.VITE_TRANSLATOR_URL }}
        file_name: .env.production
        fail_on_empty: true
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        file: .docker/Dockerfile
        tags: ghcr.io/${{ github.repository }}:latest

