name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_VITE_MAL_CLIENT_ID: ${{ secrets.VITE_MAL_CLIENT_ID }}
          envkey_VITE_API_URL: http://api.animmendation.com.br
          envkey_VITE_TRANSLATOR_URL: http://api.animmendation.com.br/translate
          file_name: .env.production.local


      - name: Test envfile
        run: |
          ls -a
          cat .env.production.local

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: .docker/Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest
