name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: set environment variables
      uses: allenevans/set-env@v2.0.0
      with:
        VITE_MAL_CLIENT_ID: ${{ secrets.VITE_MAL_CLIENT_ID }}
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        VITE_TRANSLATOR_URL: ${{ secrets.VITE_TRANSLATOR_URL }}
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        file: .docker/Dockerfile
        tags: ghcr.io/${{ github.repository }}:latest

